### ISSUE TITLE
read fails to return valid response on session key

### ISSUE THREAD

**Issue by pinterb** [CiscoCloud/consulkv#1]
First off, kudos.  A really simple, neat idea!  I'm attempting to perform some leader election in Consul.  I believe **consulkv lock** is working as expected.  But I was hoping to use **consulkv read** to obtain the session id for leadership discovery.  fwiw...using curl on kv endpoint works fine.

Perhaps it's user error, or a lack of Consul operational experience, but here are the steps to reproduce:  

``` sh
root@1d85649dbffb:/# consulkv lock --consul=consulhost:8500 --ttl="60s" service/test/nolikey 
ea52849e-d1c6-a81e-89b0-efd94f33d78a
```

``` sh
root@1d85649dbffb:/# consulkv read --consul=consulhost:8500 service/test/nolikey

```

``` sh
root@1d85649dbffb:/# curl http://consulhost:8500/v1/kv/service/test/nolikey
[{"CreateIndex":1525,"ModifyIndex":1525,"LockIndex":1,"Key":"service/test/nolikey","Flags":3304740253564472344,"Value":null,"Session":"ea52849e-d1c6-a81e-89b0-efd94f33d78a"}]
```

**Comment by ChrisAubuchon** [comment]
By default, `consulkv` only returns the value in a `read` command. Add `--fields=session` to your read command to return the session id.

**Comment by pinterb** [comment]
Ah...makes sense.  Thanks.
